#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TAG_BLOCK "Block"
#define TAG_PARAMETER "Parameter"

#define PROPERTY_NAME "name"
#define PROPERTY_VARIABLE "variable"
#define PROPERTY_UI "ui"
#define PROPERTY_FILE_EXTENSION "extension"
#define PROPERTY_VALUE "value"
#define PROPERTY_LABELS "labels"
#define PROPERTY_VALUES "values"
#define PROPERTY_TYPE "type"
#define PROPERTY_INT "int"
#define PROPERTY_DOUBLE "double"
#define PROPERTY_STRING "string"
#define PROPERTY_TABLE "table"
#define PROPERTY_TYPE_OF_KEY "TYPE OF KEY"
#define PROPERTY_COLUMN_LABELS "columnlabels"
#define PROPERTY_COLUMN_VARIABLES "columnvariables"
#define PROPERTY_TARGET_ROW "targetrow"
#define PROPERTY_NROWS "nrows"
#define PROPERTY_TARGET_VARIABLE "targetvariable"
#define PROPERTY_USER_VALUE "userValue"
#define PROPERTY_VARIABLE_METHOD "variablemethod"
#define PROPERTY_VARIABLE_METHOD1 "method1"
#define PROPERTY_VARIABLE_METHOD2 "method2"
#define PROPERTY_DEFAULT "default"
#define PROPERTY_AUTO "auto"
#define WIDGET_LINE_EDIT "lineedit"
#define WIDGET_FILE_PICKER "filepicker"
#define WIDGET_EXCLUSIVE_CHOICE "exclusivechoice"
#define WIDGET_GENERIC_PARAMETER_TABLE "genericparametertable"

#define WIDGET_DOUBLE_TRIPLET "double_triplet"
#define PARAMETER_TYPE_OF_KEY "qt_type_of_key_qt"
#define COLLAPSIBLEBLOCK_OBJECT_NAME "collapsibleblock"

#endif // CONSTANTS_H
